export default [
    {   
        id: 1,
        url: "property-1.jpg",
        imageName: "COVA Home Realty",
        price: 710.68,
        address: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        bed: 3,
        bath: 2,
        sqft: 1430,
    },
    {   
        id: 2,
        url: "property-2.jpg",
        imageName: "Exit Realty",
        price: 630.44,
        address: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
        bed: 5,
        bath: 4,
        sqft: 1630,
    },
    {   
        id: 3,
        url: "property-3.jpg",
        imageName: "The Real Estate Group",
        price: 475.22,
        address: "2972 Westheimer Rd. Santa Ana, Illinosis 85486",
        bed: 5,
        bath: 4,
        sqft: 1630,
    },
    {   
        id: 4,
        url: "property-4.jpg",
        imageName: "Exit Realty",
        price: 630.44,
        address: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
        bed: 5,
        bath: 4,
        sqft: 1630,
    },
    {   
        id: 5,
        url: "property-5.jpg",
        imageName: "Exit Realty",
        price: 630.44,
        address: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
        bed: 5,
        bath: 4,
        sqft: 1630,
    },
    {   
        id: 6,
        url: "property-6.jpg",
        imageName: "Exit Realty",
        price: 630.44,
        address: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
        bed: 5,
        bath: 4,
        sqft: 1630,
    },
    {   
        id: 7,
        url: "property-7.jpg",
        imageName: "Exit Realty",
        price: 630.44,
        address: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
        bed: 5,
        bath: 4,
        sqft: 1630,
    }
]